# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 485eb269a7e209fce16bf4bc806cff5f14657d44fe7c406963c64beb28de68c0d82e1a7c59c3ffb91bca7b63caf9de3c878ae10aa503bd5b75f313dd1b08eb6b

test:
  secret_key_base: 2c015c5a58b34c0e8423a591eae947cc28d222180e498c6a19b113b1d00501864b9da833f019b980a3076c750deb5ccd56e288b5245d07d0ea8f4089ab974e50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
